site_name: "Animove"
site_description: "A low-cost, easy-to-use and high-resolution system to evaluate swimming performance in zebrafish adults and embryos"
site_author: "LabMus - UFRJ"
repo_url: https://github.com/labmus-ufrj/Animove
repo_name: labmus-ufrj/Animove

theme:
  name: "material" # https://squidfunk.github.io/mkdocs-material/
#  name: "readthedocs"
#  prev_next_buttons_location : "top"
  icon:
    logo: fontawesome/solid/fish
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.path
    - navigation.tracking
    - search.suggest
    - search.highlight

#todo: change this link
site_url: https://animove-docs.vercel.app/

nav:
  - 'Home': 'index.md'
  - 'User Guide':
      - 'Installation': 'guide/installation.md'
      - 'Quick Start': 'guide/quick-start.md'
  - '1 - Tools':
      - 'Check Dependencies': 'tools/check-dependencies.md'
      - 'Create Sequential ROIs': 'tools/create-rois.md'
      - 'FFmpeg': 'tools/ffmpeg.md'
      - 'Image Calculator': 'tools/image-calculator.md'
      - 'Invert Video': 'tools/invert-video.md'
      - 'Performance Test': 'tools/performance-test.md'
      - 'Z-project': 'tools/z-project.md'
  - '2 - Processing':
      - 'Heatmaps':
          - 'Binary Heatmap Image (Larvae)': 'processing/heatmap-binary.md'
          - 'Sum Heatmap Images (Adults)': 'processing/heatmap-images.md'
          - 'Sum Heatmap Video (Adults)': 'processing/heatmap-video.md'
      - 'Tracking':
          - 'Adults Tracking': 'processing/adults-tracking.md'
          - 'Larvae Tracking': 'processing/larvae-tracking.md'
  - '3 - Analysis':
      - 'Calculate Score Gradient': 'analysis/score-gradient.md'
      - 'Calculate Score Sectors': 'analysis/score-sectors.md'
#      - 'Extract Tracking Data': 'analysis/tracking-data.md'
      - 'Extract Tracking Frequency Data': 'analysis/frequency-data.md'
      - 'Quantify Binary Heatmap': 'analysis/quantify-heatmap.md'

markdown_extensions:
  - admonition # "note" or "warning" boxes
  - pymdownx.highlight # code syntax highlighting
  - pymdownx.superfences # code boxes
  - attr_list
  - pymdownx.snippets:
      base_path: ["docs/snippets"]
      check_paths: true # This helps debug by throwing an error if the file isn't found

plugins:
  - mkdocs-video