site_name: "Animove"
site_description: "A low-cost, easy-to-use and high-resolution system to evaluate swimming performance in zebrafish adults and embryos"
site_author: "LabMus - UFRJ"
repo_url: https://github.com/labmus-ufrj/tracking-plugin/
repo_name: labmus-ufrj/tracking-plugin

theme:
  name: "material" # https://squidfunk.github.io/mkdocs-material/
#  name: "readthedocs"
#  prev_next_buttons_location : "top"
  icon:
    logo: fontawesome/solid/fish
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.path
    - navigation.tracking
    - search.suggest
    - search.highlight
site_url: https://tracking-plugin.vercel.app/

nav:
  - 'Home': 'index.md'
  - 'User Guide':
      - 'Installation': 'guide/installation.md'
      - 'Quick Start': 'guide/quick-start.md'
  - 'Tools':
      - 'FFmpeg': 'tools/ffmpeg.md'
      - 'Z-project': 'tools/z-project.md'
      - 'Image Calculator': 'tools/image-calculator.md'
      - 'Performance Test': 'tools/performance-test.md'
      - 'Invert Video': 'tools/invert-video.md'
  - 'Processing':
      - 'Heatmaps':
          - 'Sum Heatmap Images': 'processing/heatmap-images.md'
          - 'Sum Heatmap Video': 'processing/heatmap-video.md'
          - 'Binary Heatmap Image': 'processing/heatmap-binary.md'
      - 'Tracking':
          - 'Embryos Tracking': 'processing/embryos-tracking.md'
          - 'Adults Tracking': 'processing/adults-tracking.md'
  - 'Analysis':
      - 'Extract Tracking Data': 'analysis/tracking-data.md'
      - 'Calculate Score Gradient': 'analysis/score-gradient.md'
      - 'Calculate Score Sectors': 'analysis/score-sectors.md'
      - 'Embryos':
          - 'Quantify Heatmap': 'analysis/quantify-heatmap.md'
          - 'Extract Frequency Data': 'analysis/frequency-data.md'

markdown_extensions:
  - admonition # "note" or "warning" boxes
  - pymdownx.highlight # code syntax highlighting
  - pymdownx.superfences # code boxes
  - attr_list
