site_name: "ZF Utils"
site_description: "A zero-cost, easy-to-use and high-resolution system to evaluate swimming performance in zebrafish adults and embryos"
site_author: "LabMus - UFRJ"

theme:
  name: "readthedocs"
  prev_next_buttons_location : "top"

nav:
  - 'Home': 'index.md'
  - 'User Guide':
      - 'Installation': 'guide/installation.md'
      - 'Quick Start': 'guide/quick-start.md'
  - 'Tools':
      - 'FFmpeg': 'tools/ffmpeg.md'
      - 'Z-project': 'tools/z-project.md'
      - 'Image Calculator': 'tools/image-calculator.md'
  - 'Processing':
      - 'Generate Heatmap Images': 'processing/heatmap-images.md'
      - 'Generate Heatmap Video': 'processing/heatmap-video.md'
  - 'Analysis':
      - 'Extract Tracking Data': 'analysis/tracking-data.md'
      - 'Calculate Score Gradient': 'analysis/score-gradient.md'
      - 'Calculate Score Sectors': 'analysis/score-sectors.md'
      - 'Embryos':
          - 'Quantify Heatmap' : 'analysis/quantify-heatmap.md'
          - 'Extract Frequency Data' : 'analysis/frequency-data.md'

markdown_extensions:
  - admonition # "note" or "warning" boxes
  - pymdownx.highlight # code syntax highlighting
  - pymdownx.superfences # code boxes
